# This workflow ONLY reports test coverage in the logs.
# It assumes R CMD check is handled in a separate workflow.
# It is triggered on pushes and pull requests to the main/master branches.

name: Test Coverage

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  report-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # This step now only needs to install your package's dependencies and covr
      - name: Install package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr

      # NOTE: The 'Run R CMD check' step has been removed from this file.
      
      - name: Test and Report Coverage
        run: |
          # Run tests under the covr profiler to calculate coverage
          coverage <- covr::package_coverage(quiet = FALSE)
          
          # Print the detailed coverage summary to the workflow log
          print(coverage)
        shell: Rscript {0}
